remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

page:
  title: Book unique experiences in Dubrovnik 
title: Vedrana travel
description: Private and group options available

show_downloads: false
github:
  is_project_page: false
